### Site Settings ###
title               : Laurine Lafontaine
description         : AI engineer
baseurl             : "/portfolio"
open_new_tab        : true


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Laurine Lafontaine
  email             : laurine.lafontaine@outlook.fr
  github            : LafLaurine
  linkedin          : laurine-lafontaine-826545148


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    ai:
      permalink: /projects/ai/:name
    game:
      permalink: /projects/game/:name
    software:
      permalink: /projects/software/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - "*.log"
